export type PluginType = 
      'lex'
    | 'parse'
    | 'preParse'
    | 'postParse'
    | 'preLex'
    | 'postLex'
    | 'preLex'
    | 'preLoad'
    | 'generateCode'
    | 'postFilters'
    | 'preLink'
    | 'postLink'
    | 'preCodeGen'
    | 'postCodeGen'
    | 'read'
    | 'resolve'
    | 'postLoad'
    | 'preFilters'
    ;
